---
# tasks file for myatu.shorewall
- name: Debug OS Version
  debug:
    msg: "distribution: {{ ansible_distribution }}, major_version: {{ ansible_distribution_major_version }}"

- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- name: Remove incompatible firewall packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ shorewall_incompatible_packages|default([]) }}"
  when: (shorewall_package_state != "absent")

- include: shorewall.yml
  when: shorewall_run

- include: shorewall6.yml
  when: shorewall6_run
  #when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global' and shorewall6_run"

- name: Shorewall dead man's switch 
  debug:
    msg: "Skipped Shorewall configuration because dead man's switch var 'shorewall_run' is not set to true"
  when: not shorewall_run

  - name: Shorewall6 dead man's switch 
  debug:
    msg: "Skipped Shorewall6 configuration because dead man's switch var 'shorewall6_run' is not set to true"
  when: not shorewall6_run
