---
# Shorewall tasks file for Myatu.shorewall

- name: Gather Shorewall configuration variables
  set_fact:
    shorewall_conf: "{{ shorewall_conf_base|combine(shorewall_conf) }}"   

- name: Install Shorewall and dependencies
  package:
    name: "{{ item }}"
    state: "{{ shorewall_package_state }}"
  with_items: "{{ shorewall_packages }}"
  notify: 
    - enable shorewall
  tags:
    - packages

- block:
  - name: Obtain Shorewall version
    command: shorewall version
    register: shorewall_version_result
    changed_when: False

  - name: Convert Shorewall version var
    set_fact:
      shorewall_version: "{{ '.'.join( shorewall_version_result.get('stdout', '0.0').split('.')[:2] ) }}"

  - name: debug config
    debug:
      msg: "{{ shorewall_rules }}"

  - name: Generate Shorewall configuration files
    template:
      dest: "/etc/shorewall/{{ item }}"
      src: "shorewall/{{ item }}.j2"
      owner: root
      group: root
      mode: 0640
    with_items:
      - shorewall.conf
      - params
      - interfaces
      - zones
      - policy
      - rules
      - hosts
      - providers
      - tunnels
        #      - actions
      - stoppedrules
      - rtrules
      - mangle
      - routes
      - tcinterfaces
    notify:
      - restart shorewall
    tags:
      - configuration

  - name: debug shorewall_version
    debug:
      var: shorewall_version

  - name: Generate Shorewall masq file
    template:
      dest: "/etc/shorewall/{{ item }}"
      src: "shorewall/{{ item }}.j2"
      owner: root
      group: root
      mode: 0640
    with_items:
      - masq
    notify:
      - restart shorewall
    tags:
      - configuration
    when: (shorewall_version|float < 5.0)

  - name: Generate Shorewall snat file
    template:
      dest: "/etc/shorewall/{{ item }}"
      src: "shorewall/{{ item }}.j2"
      owner: root
      group: root
      mode: 0640
    with_items:
      - snat
    notify:
      - restart shorewall
    tags:
      - configuration
    when: (shorewall_version|float >= 5.0)

  - name: Verify Shorewall configuration
    command: shorewall check
    changed_when: False
    tags:
      - tests

  - name: Generate Shorewall service configuration
    template:
      dest: /etc/default/shorewall
      src: default/shorewall.j2
      owner: root
      group: root
      mode: 0640
    notify: 
      - restart shorewall
    tags:
      - configuration
    when: (shorewall_package_state != "absent")

  - name: Enable Shorewall service in systemd
    systemd:
      name: shorewall
      enabled: yes
      masked: no
 
